extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.tracing]
pipeline = [
    "bril2json",
    "brilitc -p {args}",
    "./add_trace.py",
    "brili -p {args}",
]